#define WIFI_SSID "<Your WiFi SSID>"
#define WIFI_PASSWD "<Your WiFi Password>"
#define PROJECT_ID "<Your Project ID>"
#define REGION "<Your Project's Region>"
#define REGISTRY "<Your Registry name>"
#define DEVICE "<Your device name>"
